/** Tailwind arbitrary properties for the low-glare Calm White theme. */
export const calmWhiteThemeClasses = [
  "[&[data-theme=light][data-theme=light]]:[color-scheme:light]",
  "[&[data-theme=light][data-theme=light]]:[--color-base-00:#fdfdfc]",
  "[&[data-theme=light][data-theme=light]]:[--color-base-05:#fbfbfa]",
  "[&[data-theme=light][data-theme=light]]:[--color-base-10:#f8f8f7]",
  "[&[data-theme=light][data-theme=light]]:[--color-base-20:#f2f2f1]",
  "[&[data-theme=light][data-theme=light]]:[--color-base-25:#eaeae9]",
  "[&[data-theme=light][data-theme=light]]:[--color-base-30:#dededd]",
  "[&[data-theme=light][data-theme=light]]:[--color-base-35:#cccccb]",
  "[&[data-theme=light][data-theme=light]]:[--color-base-40:#aaaaa8]",
  "[&[data-theme=light][data-theme=light]]:[--color-base-50:#777775]",
  "[&[data-theme=light][data-theme=light]]:[--color-base-60:#555553]",
  "[&[data-theme=light][data-theme=light]]:[--color-base-70:#333331]",
  "[&[data-theme=light][data-theme=light]]:[--color-base-100:#171715]",

  "[&[data-theme=light][data-theme=light]]:[--bg-primary:#fdfdfc]",
  "[&[data-theme=light][data-theme=light]]:[--bg-secondary:#fbfbfa]",
  "[&[data-theme=light][data-theme=light]]:[--bg-tertiary:#f7f7f6]",
  "[&[data-theme=light][data-theme=light]]:[--bg-elevated:#ffffff]",
  "[&[data-theme=light][data-theme=light]]:[--bg-input:#ffffff]",
  "[&[data-theme=light][data-theme=light]]:[--bg-hover:rgba(23,_23,_21,_0.055)]",
  "[&[data-theme=light][data-theme=light]]:[--bg-active:rgba(23,_23,_21,_0.09)]",
  "[&[data-theme=light][data-theme=light]]:[--bg-glass:rgba(253,_253,_252,_0.96)]",

  "[&[data-theme=light][data-theme=light]]:[--text-primary:#171715]",
  "[&[data-theme=light][data-theme=light]]:[--text-secondary:#292927]",
  "[&[data-theme=light][data-theme=light]]:[--text-tertiary:#3b3b38]",
  "[&[data-theme=light][data-theme=light]]:[--text-muted:#50504c]",
  "[&[data-theme=light][data-theme=light]]:[--text-faint:#686862]",
  "[&[data-theme=light][data-theme=light]]:[--text-link:#2f5f89]",

  "[&[data-theme=light][data-theme=light]]:[--accent-color:#262624]",
  "[&[data-theme=light][data-theme=light]]:[--color-accent:#262624]",
  "[&[data-theme=light][data-theme=light]]:[--color-accent-1:#111110]",
  "[&[data-theme=light][data-theme=light]]:[--color-accent-2:#000000]",
  "[&[data-theme=light][data-theme=light]]:[--text-on-accent:#ffffff]",
  "[&[data-theme=light][data-theme=light]]:[--accent-glow:rgba(23,_23,_21,_0.09)]",
  "[&[data-theme=light][data-theme=light]]:[--accent-gradient:linear-gradient(135deg,_#333331,_#171715)]",

  "[&[data-theme=light][data-theme=light]]:[--border-subtle:rgba(23,_23,_21,_0.1)]",
  "[&[data-theme=light][data-theme=light]]:[--border-medium:rgba(23,_23,_21,_0.17)]",
  "[&[data-theme=light][data-theme=light]]:[--border-strong:rgba(23,_23,_21,_0.25)]",
  "[&[data-theme=light][data-theme=light]]:[--divider-color:rgba(23,_23,_21,_0.13)]",
  "[&[data-theme=light][data-theme=light]]:[--scrollbar-thumb:rgba(23,_23,_21,_0.22)]",
  "[&[data-theme=light][data-theme=light]]:[--scrollbar-thumb-hover:rgba(23,_23,_21,_0.36)]",
  "[&[data-theme=light][data-theme=light]]:[--shadow-sm:0_1px_2px_rgba(23,_23,_21,_0.06)]",
  "[&[data-theme=light][data-theme=light]]:[--shadow-md:0_4px_12px_rgba(23,_23,_21,_0.1)]",
  "[&[data-theme=light][data-theme=light]]:[--shadow-lg:0_8px_28px_rgba(23,_23,_21,_0.14)]",

  "[&[data-theme=light][data-theme=light]]:[--tab-container-background:var(--bg-secondary)]",
  "[&[data-theme=light][data-theme=light]]:[--tab-background-active:var(--bg-primary)]",
  "[&[data-theme=light][data-theme=light]]:[--tab-text-color:#50504c]",
  "[&[data-theme=light][data-theme=light]]:[--tab-text-color-active:#171715]",
  "[&[data-theme=light][data-theme=light]]:[--tab-text-color-focused:#3b3b38]",
  "[&[data-theme=light][data-theme=light]]:[--tab-text-color-focused-active:#171715]",
  "[&[data-theme=light][data-theme=light]]:[--tab-text-color-focused-active-current:#171715]",
  "[&[data-theme=light][data-theme=light]]:[--tab-outline-color:transparent]",
  "[&[data-theme=light][data-theme=light]]:[--tab-divider-color:var(--divider-color)]",
  "[&[data-theme=light][data-theme=light]_.titlebar-tab.active]:!border-[var(--divider-color)]",

  "[&[data-theme=light][data-theme=light]]:[--nav-item-color:#292927]",
  "[&[data-theme=light][data-theme=light]]:[--nav-item-color-hover:#171715]",
  "[&[data-theme=light][data-theme=light]]:[--nav-item-color-active:#171715]",
  "[&[data-theme=light][data-theme=light]]:[--nav-item-color-selected:#171715]",
  "[&[data-theme=light][data-theme=light]]:[--nav-item-background-selected:rgba(23,_23,_21,_0.08)]",
  "[&[data-theme=light][data-theme=light]]:[--titlebar-background:var(--bg-secondary)]",
  "[&[data-theme=light][data-theme=light]]:[--titlebar-background-focused:var(--bg-tertiary)]",
  "[&[data-theme=light][data-theme=light]]:[--titlebar-text-color:#3b3b38]",
  "[&[data-theme=light][data-theme=light]]:[--titlebar-text-color-focused:#171715]",
  "[&[data-theme=light][data-theme=light]]:[--status-bar-background:var(--bg-secondary)]",
  "[&[data-theme=light][data-theme=light]]:[--status-bar-text-color:#3b3b38]",

  "[&[data-theme=light][data-theme=light]]:[--editor-caret:#171715]",
  "[&[data-theme=light][data-theme=light]]:[--editor-selection:rgba(47,_95,_137,_0.16)]",
  "[&[data-theme=light][data-theme=light]]:[--editor-selection-focused:rgba(47,_95,_137,_0.24)]",
  "[&[data-theme=light][data-theme=light]]:[--editor-active-line:rgba(23,_23,_21,_0.025)]",
  "[&[data-theme=light][data-theme=light]]:[--editor-heading:#171715]",
  "[&[data-theme=light][data-theme=light]]:[--editor-heading-marker:#50504c]",
  "[&[data-theme=light][data-theme=light]]:[--editor-link:#2f5f89]",
  "[&[data-theme=light][data-theme=light]]:[--editor-link-hover:#214766]",
  "[&[data-theme=light][data-theme=light]]:[--editor-tag:#365f52]",
  "[&[data-theme=light][data-theme=light]]:[--editor-tag-bg:rgba(54,_95,_82,_0.1)]",
  "[&[data-theme=light][data-theme=light]]:[--editor-code:#8a4b1f]",
  "[&[data-theme=light][data-theme=light]]:[--editor-muted-token:#50504c]",
  "[&[data-theme=light][data-theme=light]]:[--editor-emphasis:#171715]",
  "[&[data-theme=light][data-theme=light]]:[--editor-search-match:rgba(232,_181,_50,_0.25)]",
  "[&[data-theme=light][data-theme=light]]:[--editor-search-match-border:rgba(175,_126,_15,_0.5)]",
  "[&[data-theme=light][data-theme=light]]:[--editor-search-active:rgba(232,_166,_50,_0.34)]",
  "[&[data-theme=light][data-theme=light]]:[--editor-search-active-border:rgba(151,_96,_9,_0.72)]",

  "[&[data-theme=light][data-theme=light]]:[--graph-edge-color:rgba(23,_23,_21,_0.3)]",
  "[&[data-theme=light][data-theme=light]]:[--graph-node-color:#262624]",
  "[&[data-theme=light][data-theme=light]]:[--color-red:#c23838]",
  "[&[data-theme=light][data-theme=light]]:[--color-orange:#b65b18]",
  "[&[data-theme=light][data-theme=light]]:[--color-yellow:#947200]",
  "[&[data-theme=light][data-theme=light]]:[--color-green:#347446]",
  "[&[data-theme=light][data-theme=light]]:[--color-cyan:#267675]",
  "[&[data-theme=light][data-theme=light]]:[--color-blue:#2f5f89]",
  "[&[data-theme=light][data-theme=light]]:[--color-purple:#6b4e91]",
  "[&[data-theme=light][data-theme=light]]:[--color-pink:#9c466d]",
].join(" ");
