/** Tailwind arbitrary properties for the built-in application themes. */
const parchmentThemeClasses = [
  "[&[data-theme=parchment]]:[color-scheme:light]",
  "[&[data-theme=parchment]]:[--color-base-00:#faf5d0]",
  "[&[data-theme=parchment]]:[--color-base-05:#faf5d0]",
  "[&[data-theme=parchment]]:[--color-base-10:#faf5d0]",
  "[&[data-theme=parchment]]:[--color-base-20:#f9f4cf]",
  "[&[data-theme=parchment]]:[--color-base-25:#f8f2cc]",
  "[&[data-theme=parchment]]:[--color-base-30:#f7f0c8]",
  "[&[data-theme=parchment]]:[--color-base-35:#f5edc2]",
  "[&[data-theme=parchment]]:[--color-base-40:#ad9866]",
  "[&[data-theme=parchment]]:[--color-base-50:#8b7548]",
  "[&[data-theme=parchment]]:[--color-base-60:#6e5935]",
  "[&[data-theme=parchment]]:[--color-base-70:#514229]",
  "[&[data-theme=parchment]]:[--color-base-100:#312719]",

  "[&[data-theme=parchment]]:[--bg-primary:#faf5d0]",
  "[&[data-theme=parchment]]:[--bg-secondary:#faf5d0]",
  "[&[data-theme=parchment]]:[--bg-tertiary:#f9f4cf]",
  "[&[data-theme=parchment]]:[--bg-elevated:#fffbed]",
  "[&[data-theme=parchment]]:[--bg-input:#fffbed]",
  "[&[data-theme=parchment]]:[--bg-hover:rgba(81,_66,_41,_0.035)]",
  "[&[data-theme=parchment]]:[--bg-active:rgba(81,_66,_41,_0.065)]",
  "[&[data-theme=parchment]]:[--bg-glass:rgba(250,_245,_208,_0.95)]",

  "[&[data-theme=parchment]]:[--text-primary:#000000]",
  "[&[data-theme=parchment]]:[--text-secondary:#000000]",
  "[&[data-theme=parchment]]:[--text-tertiary:#000000]",
  "[&[data-theme=parchment]]:[--text-muted:#000000]",
  "[&[data-theme=parchment]]:[--text-faint:#000000]",
  "[&[data-theme=parchment]]:[--text-link:#8f5424]",

  "[&[data-theme=parchment]]:[--accent-color:#a6692e]",
  "[&[data-theme=parchment]]:[--color-accent:#a6692e]",
  "[&[data-theme=parchment]]:[--color-accent-1:#8f5424]",
  "[&[data-theme=parchment]]:[--color-accent-2:#75431c]",
  "[&[data-theme=parchment]]:[--text-on-accent:#fffaf0]",
  "[&[data-theme=parchment]]:[--accent-glow:rgba(166,_105,_46,_0.12)]",
  "[&[data-theme=parchment]]:[--accent-gradient:linear-gradient(135deg,_#b77738,_#8f5424)]",

  "[&[data-theme=parchment]]:[--scrollbar-thumb:rgba(81,_66,_41,_0.18)]",
  "[&[data-theme=parchment]]:[--scrollbar-thumb-hover:rgba(81,_66,_41,_0.32)]",
  "[&[data-theme=parchment]]:[--border-subtle:rgba(0,_0,_0,_0.14)]",
  "[&[data-theme=parchment]]:[--border-medium:rgba(0,_0,_0,_0.2)]",
  "[&[data-theme=parchment]]:[--border-strong:rgba(0,_0,_0,_0.28)]",
  "[&[data-theme=parchment]]:[--divider-color:rgba(0,_0,_0,_0.18)]",
  "[&[data-theme=parchment]]:[--shadow-sm:0_1px_2px_rgba(49,_39,_25,_0.05)]",
  "[&[data-theme=parchment]]:[--shadow-md:0_4px_12px_rgba(49,_39,_25,_0.09)]",
  "[&[data-theme=parchment]]:[--shadow-lg:0_8px_32px_rgba(49,_39,_25,_0.13)]",
  "[&[data-theme=parchment]]:[--nav-item-background-selected:rgba(166,_105,_46,_0.1)]",
  "[&[data-theme=parchment]]:[--tab-text-color:#756b50]",
  "[&[data-theme=parchment]]:[--tab-text-color-active:#000000]",
  "[&[data-theme=parchment]]:[--tab-text-color-focused:#756b50]",
  "[&[data-theme=parchment]]:[--tab-text-color-focused-active:#000000]",
  "[&[data-theme=parchment]]:[--tab-text-color-focused-active-current:#000000]",
  "[&[data-theme=parchment]]:[--tab-outline-color:transparent]",
  "[&[data-theme=parchment]]:[--tab-divider-color:rgba(0,_0,_0,_0.18)]",
  "[&[data-theme=parchment]_.titlebar-tab.active]:!border-[var(--divider-color)]",

  "[&[data-theme=parchment]]:[--editor-caret:#8f5424]",
  "[&[data-theme=parchment]]:[--editor-selection:rgba(166,_105,_46,_0.18)]",
  "[&[data-theme=parchment]]:[--editor-selection-focused:rgba(166,_105,_46,_0.28)]",
  "[&[data-theme=parchment]]:[--editor-active-line:rgba(81,_66,_41,_0.025)]",
  "[&[data-theme=parchment]]:[--editor-heading:#000000]",
  "[&[data-theme=parchment]]:[--editor-heading-marker:#000000]",
  "[&[data-theme=parchment]]:[--editor-link:#8f5424]",
  "[&[data-theme=parchment]]:[--editor-link-hover:#75431c]",
  "[&[data-theme=parchment]]:[--editor-tag:#775b25]",
  "[&[data-theme=parchment]]:[--editor-tag-bg:rgba(143,_84,_36,_0.11)]",
  "[&[data-theme=parchment]]:[--editor-code:#8a4b1f]",
  "[&[data-theme=parchment]]:[--editor-muted-token:#000000]",
  "[&[data-theme=parchment]]:[--editor-emphasis:#000000]",
  "[&[data-theme=parchment]]:[--editor-search-match:rgba(214,_151,_43,_0.25)]",
  "[&[data-theme=parchment]]:[--editor-search-match-border:rgba(174,_111,_22,_0.52)]",
  "[&[data-theme=parchment]]:[--editor-search-active:rgba(202,_122,_26,_0.34)]",
  "[&[data-theme=parchment]]:[--editor-search-active-border:rgba(143,_84,_36,_0.76)]",

  "[&[data-theme=parchment]]:[--titlebar-background:var(--bg-secondary)]",
  "[&[data-theme=parchment]]:[--titlebar-background-focused:var(--bg-tertiary)]",
  "[&[data-theme=parchment]]:[--graph-edge-color:rgba(81,_66,_41,_0.32)]",
  "[&[data-theme=parchment]]:[--graph-node-color:#a6692e]",

  "[&[data-theme=parchment]]:[--color-red:#c73f3f]",
  "[&[data-theme=parchment]]:[--color-orange:#b85d17]",
  "[&[data-theme=parchment]]:[--color-yellow:#9b7900]",
  "[&[data-theme=parchment]]:[--color-green:#4f7d35]",
  "[&[data-theme=parchment]]:[--color-cyan:#267a76]",
  "[&[data-theme=parchment]]:[--color-blue:#376ca3]",
  "[&[data-theme=parchment]]:[--color-purple:#73569b]",
  "[&[data-theme=parchment]]:[--color-pink:#a34f75]",
  "[&[data-theme=parchment]]:[--color-red-rgb:199,_63,_63]",
  "[&[data-theme=parchment]]:[--color-orange-rgb:184,_93,_23]",
  "[&[data-theme=parchment]]:[--color-yellow-rgb:155,_121,_0]",
  "[&[data-theme=parchment]]:[--color-green-rgb:79,_125,_53]",
  "[&[data-theme=parchment]]:[--color-cyan-rgb:38,_122,_118]",
  "[&[data-theme=parchment]]:[--color-blue-rgb:55,_108,_163]",
  "[&[data-theme=parchment]]:[--color-purple-rgb:115,_86,_155]",
  "[&[data-theme=parchment]]:[--color-pink-rgb:163,_79,_117]",
  "[&[data-theme=parchment]]:[--mono-rgb-0:255,_255,_255]",
  "[&[data-theme=parchment]]:[--mono-rgb-100:0,_0,_0]",
  "[&[data-theme=parchment]]:[--background-modifier-error-rgb:199,_63,_63]",
  "[&[data-theme=parchment]]:[--background-modifier-success-rgb:79,_125,_53]",
].join(" ");

const calmWhiteThemeClasses = [
  "[&[data-theme=light][data-theme=light]]:[color-scheme:light]",
  "[&[data-theme=light][data-theme=light]]:[--color-base-00:#fdfdfc]",
  "[&[data-theme=light][data-theme=light]]:[--color-base-05:#fbfbfa]",
  "[&[data-theme=light][data-theme=light]]:[--color-base-10:#f8f8f7]",
  "[&[data-theme=light][data-theme=light]]:[--color-base-20:#f2f2f1]",
  "[&[data-theme=light][data-theme=light]]:[--color-base-25:#eaeae9]",
  "[&[data-theme=light][data-theme=light]]:[--color-base-30:#dededd]",
  "[&[data-theme=light][data-theme=light]]:[--color-base-35:#cccccb]",
  "[&[data-theme=light][data-theme=light]]:[--color-base-40:#aaaaa8]",
  "[&[data-theme=light][data-theme=light]]:[--color-base-50:#777775]",
  "[&[data-theme=light][data-theme=light]]:[--color-base-60:#555553]",
  "[&[data-theme=light][data-theme=light]]:[--color-base-70:#333331]",
  "[&[data-theme=light][data-theme=light]]:[--color-base-100:#171715]",

  "[&[data-theme=light][data-theme=light]]:[--bg-primary:#fdfdfc]",
  "[&[data-theme=light][data-theme=light]]:[--bg-secondary:#fbfbfa]",
  "[&[data-theme=light][data-theme=light]]:[--bg-tertiary:#f7f7f6]",
  "[&[data-theme=light][data-theme=light]]:[--bg-elevated:#ffffff]",
  "[&[data-theme=light][data-theme=light]]:[--bg-input:#ffffff]",
  "[&[data-theme=light][data-theme=light]]:[--bg-hover:rgba(23,_23,_21,_0.055)]",
  "[&[data-theme=light][data-theme=light]]:[--bg-active:rgba(23,_23,_21,_0.09)]",
  "[&[data-theme=light][data-theme=light]]:[--bg-glass:rgba(253,_253,_252,_0.96)]",

  "[&[data-theme=light][data-theme=light]]:[--text-primary:#171715]",
  "[&[data-theme=light][data-theme=light]]:[--text-secondary:#292927]",
  "[&[data-theme=light][data-theme=light]]:[--text-tertiary:#3b3b38]",
  "[&[data-theme=light][data-theme=light]]:[--text-muted:#50504c]",
  "[&[data-theme=light][data-theme=light]]:[--text-faint:#686862]",
  "[&[data-theme=light][data-theme=light]]:[--text-link:#2f5f89]",

  "[&[data-theme=light][data-theme=light]]:[--accent-color:#262624]",
  "[&[data-theme=light][data-theme=light]]:[--color-accent:#262624]",
  "[&[data-theme=light][data-theme=light]]:[--color-accent-1:#111110]",
  "[&[data-theme=light][data-theme=light]]:[--color-accent-2:#000000]",
  "[&[data-theme=light][data-theme=light]]:[--text-on-accent:#ffffff]",
  "[&[data-theme=light][data-theme=light]]:[--accent-glow:rgba(23,_23,_21,_0.09)]",
  "[&[data-theme=light][data-theme=light]]:[--accent-gradient:linear-gradient(135deg,_#333331,_#171715)]",

  "[&[data-theme=light][data-theme=light]]:[--border-subtle:rgba(23,_23,_21,_0.1)]",
  "[&[data-theme=light][data-theme=light]]:[--border-medium:rgba(23,_23,_21,_0.17)]",
  "[&[data-theme=light][data-theme=light]]:[--border-strong:rgba(23,_23,_21,_0.25)]",
  "[&[data-theme=light][data-theme=light]]:[--divider-color:rgba(23,_23,_21,_0.13)]",
  "[&[data-theme=light][data-theme=light]]:[--scrollbar-thumb:rgba(23,_23,_21,_0.22)]",
  "[&[data-theme=light][data-theme=light]]:[--scrollbar-thumb-hover:rgba(23,_23,_21,_0.36)]",
  "[&[data-theme=light][data-theme=light]]:[--shadow-sm:0_1px_2px_rgba(23,_23,_21,_0.06)]",
  "[&[data-theme=light][data-theme=light]]:[--shadow-md:0_4px_12px_rgba(23,_23,_21,_0.1)]",
  "[&[data-theme=light][data-theme=light]]:[--shadow-lg:0_8px_28px_rgba(23,_23,_21,_0.14)]",

  "[&[data-theme=light][data-theme=light]]:[--tab-container-background:var(--bg-secondary)]",
  "[&[data-theme=light][data-theme=light]]:[--tab-background-active:var(--bg-primary)]",
  "[&[data-theme=light][data-theme=light]]:[--tab-text-color:#50504c]",
  "[&[data-theme=light][data-theme=light]]:[--tab-text-color-active:#171715]",
  "[&[data-theme=light][data-theme=light]]:[--tab-text-color-focused:#3b3b38]",
  "[&[data-theme=light][data-theme=light]]:[--tab-text-color-focused-active:#171715]",
  "[&[data-theme=light][data-theme=light]]:[--tab-text-color-focused-active-current:#171715]",
  "[&[data-theme=light][data-theme=light]]:[--tab-outline-color:transparent]",
  "[&[data-theme=light][data-theme=light]]:[--tab-divider-color:var(--divider-color)]",
  "[&[data-theme=light][data-theme=light]_.titlebar-tab.active]:!border-[var(--divider-color)]",

  "[&[data-theme=light][data-theme=light]]:[--nav-item-color:#292927]",
  "[&[data-theme=light][data-theme=light]]:[--nav-item-color-hover:#171715]",
  "[&[data-theme=light][data-theme=light]]:[--nav-item-color-active:#171715]",
  "[&[data-theme=light][data-theme=light]]:[--nav-item-color-selected:#171715]",
  "[&[data-theme=light][data-theme=light]]:[--nav-item-background-selected:rgba(23,_23,_21,_0.08)]",
  "[&[data-theme=light][data-theme=light]]:[--titlebar-background:var(--bg-secondary)]",
  "[&[data-theme=light][data-theme=light]]:[--titlebar-background-focused:var(--bg-tertiary)]",
  "[&[data-theme=light][data-theme=light]]:[--titlebar-text-color:#3b3b38]",
  "[&[data-theme=light][data-theme=light]]:[--titlebar-text-color-focused:#171715]",
  "[&[data-theme=light][data-theme=light]]:[--status-bar-background:var(--bg-secondary)]",
  "[&[data-theme=light][data-theme=light]]:[--status-bar-text-color:#3b3b38]",

  "[&[data-theme=light][data-theme=light]]:[--editor-caret:#171715]",
  "[&[data-theme=light][data-theme=light]]:[--editor-selection:rgba(47,_95,_137,_0.16)]",
  "[&[data-theme=light][data-theme=light]]:[--editor-selection-focused:rgba(47,_95,_137,_0.24)]",
  "[&[data-theme=light][data-theme=light]]:[--editor-active-line:rgba(23,_23,_21,_0.025)]",
  "[&[data-theme=light][data-theme=light]]:[--editor-heading:#171715]",
  "[&[data-theme=light][data-theme=light]]e:[--editor-heading-marker:#50504c]",
  "[&[data-theme=light][data-theme=light]]:[--editor-link:#2f5f89]",
  "[&[data-theme=light][data-theme=light]]:[--editor-link-hover:#214766]",
  "[&[data-theme=light][data-theme=light]]:[--editor-tag:#365f52]",
  "[&[data-theme=light][data-theme=light]]:[--editor-tag-bg:rgba(54,_95,_82,_0.1)]",
  "[&[data-theme=light][data-theme=light]]:[--editor-code:#8a4b1f]",
  "[&[data-theme=light][data-theme=light]]:[--editor-muted-token:#50504c]",
  "[&[data-theme=light][data-theme=light]]:[--editor-emphasis:#171715]",
  "[&[data-theme=light][data-theme=light]]:[--editor-search-match:rgba(232,_181,_50,_0.25)]",
  "[&[data-theme=light][data-theme=light]]:[--editor-search-match-border:rgba(175,_126,_15,_0.5)]",
  "[&[data-theme=light][data-theme=light]]:[--editor-search-active:rgba(232,_166,_50,_0.34)]",
  "[&[data-theme=light][data-theme=light]]:[--editor-search-active-border:rgba(151,_96,_9,_0.72)]",

  "[&[data-theme=light][data-theme=light]]:[--graph-edge-color:rgba(23,_23,_21,_0.3)]",
  "[&[data-theme=light][data-theme=light]]:[--graph-node-color:#262624]",
  "[&[data-theme=light][data-theme=light]]:[--color-red:#c23838]",
  "[&[data-theme=light][data-theme=light]]:[--color-orange:#b65b18]",
  "[&[data-theme=light][data-theme=light]]:[--color-yellow:#947200]",
  "[&[data-theme=light][data-theme=light]]:[--color-green:#347446]",
  "[&[data-theme=light][data-theme=light]]:[--color-cyan:#267675]",
  "[&[data-theme=light][data-theme=light]]:[--color-blue:#2f5f89]",
  "[&[data-theme=light][data-theme=light]]:[--color-purple:#6b4e91]",
  "[&[data-theme=light][data-theme=light]]:[--color-pink:#9c466d]",
].join(" ");

export const themeClasses = `${parchmentThemeClasses} ${calmWhiteThemeClasses}`;
